[package]
name = "range_ranger"
version = "0.1.0"
authors = ["Julien Roncaglia <julien@roncaglia.fr>"]
edition = "2018"
rust-version = "1.38"
license = "MIT"
description = "A range library"

[dependencies]

[dev-dependencies]
chrono = "0.4"
assert_matches = "1.5"
