name: CI

on:
  push:
  pull_request:

env:
  RUSTFLAGS: '-Dwarnings'
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, stable, 1.71.0]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo build
      - run: cargo test
      - run: cargo test --release
      - run: cargo build --no-default-features
      - run: cargo test --tests --no-default-features
      - run: cargo test --tests --no-default-features --release
      - run: cargo bench --no-run
        if: matrix.rust == 'nightly'

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@b2d072a15ba9e799dbc505c707140d9f33237405 # clippy
      - run: cargo clippy --all-targets --all-features --tests --benches -- -Dclippy::all -Dclippy::pedantic
